theme: jekyll-theme-minimal
title: Hello fellow researchers and brain imaging enthusiasts! 
description: Have you ever felt like fMRI is confusing? Imaging analysis making you feel like a big dumb baby? Alas, I too have felt this way. Because of this I decided to create this site, so that perhaps we can put together a few brain cells and do some amazing science! Let's goooooooo....
